PARSER_BEGIN(CSharpLexer)


public class CSharpLexer {

  public static void main(String args[]) throws ParseException {
    CSharpLexer lexer = new CSharpLexer(System.in);
    lexer.CSharpLexer();   
    }
  }

PARSER_END(CSharpLexer)

SKIP: { 

    //whitespace
    " "
    |"\t"
    |"\n"
    |"\r"
    
    //comments
    //comments
    | <"//" (~["\n","\r"])*>
    | <"/*" (~["*"])* "*" (~["/"] (~["*"])* "*")* "/">

}

TOKEN : {
    //keywords

    <

 }

