/* CSharpLexerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. CSharpLexerTokenManager.java */

/** Token Manager. */
public class CSharpLexerTokenManager implements CSharpLexerConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffffffff80L) != 0L || (active1 & 0xffffffffffffffffL) != 0L || (active2 & 0x3L) != 0L)
         {
            jjmatchedKind = 130;
            return 1;
         }
         if ((active2 & 0x840000000000L) != 0L)
            return 6;
         if ((active2 & 0x4080L) != 0L)
            return 72;
         return -1;
      case 1:
         if ((active0 & 0xfffff05ffe7fee80L) != 0L || (active1 & 0xfff1fe7feaffffffL) != 0L || (active2 & 0x3L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 130;
               jjmatchedPos = 1;
            }
            return 1;
         }
         if ((active0 & 0xfa001801100L) != 0L || (active1 & 0xe018015000000L) != 0L)
            return 1;
         return -1;
      case 2:
         if ((active0 & 0xfbf77053ff7ffe80L) != 0L || (active1 & 0xdbf93aefef6ffeffL) != 0L || (active2 & 0x3L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 130;
               jjmatchedPos = 2;
            }
            return 1;
         }
         if ((active0 & 0x408870c00000000L) != 0L || (active1 & 0x2400c51000900100L) != 0L)
            return 1;
         return -1;
      case 3:
         if ((active0 & 0xfbf6464bf97f4880L) != 0L || (active1 & 0x9bf99863ed6dfa5fL) != 0L || (active2 & 0x2L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 3;
            return 1;
         }
         if ((active0 & 0x130100600b600L) != 0L || (active1 & 0x4000238c020204a0L) != 0L || (active2 & 0x1L) != 0L)
            return 1;
         return -1;
      case 4:
         if ((active0 & 0xabf64648b1790080L) != 0L || (active1 & 0xbf89821e125721fL) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 4;
            return 1;
         }
         if ((active0 & 0x5000000348064800L) != 0L || (active1 & 0x900100420c488840L) != 0L || (active2 & 0x2L) != 0L)
            return 1;
         return -1;
      case 5:
         if ((active0 & 0xa922000021000000L) != 0L || (active1 & 0x36010208020621eL) != 0L)
            return 1;
         if ((active0 & 0x2d4464890790080L) != 0L || (active1 & 0x898880161051001L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 5;
            return 1;
         }
         return -1;
      case 6:
         if ((active0 & 0x294464010480080L) != 0L || (active1 & 0x880000121041001L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 6;
            return 1;
         }
         if ((active0 & 0x40000880310000L) != 0L || (active1 & 0x18880040010000L) != 0L)
            return 1;
         return -1;
      case 7:
         if ((active0 & 0x80420000000000L) != 0L || (active1 & 0x800000121001001L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 7;
            return 1;
         }
         if ((active0 & 0x214044010480080L) != 0L || (active1 & 0x80000000040000L) != 0L)
            return 1;
         return -1;
      case 8:
         if ((active0 & 0x80420000000000L) != 0L || (active1 & 0x800000101001000L) != 0L)
            return 1;
         if ((active1 & 0x20000001L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 8;
            return 1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 152;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20000L);
      case 37:
         jjmatchedKind = 143;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x100L);
      case 38:
         jjmatchedKind = 160;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x8400000L);
      case 40:
         return jjStopAtPos(0, 178);
      case 41:
         return jjStopAtPos(0, 179);
      case 42:
         jjmatchedKind = 141;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x40L);
      case 43:
         jjmatchedKind = 139;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x210L);
      case 44:
         return jjStopAtPos(0, 176);
      case 45:
         jjmatchedKind = 140;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20000000420L);
      case 46:
         jjmatchedKind = 175;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x40000000000L);
      case 47:
         jjmatchedKind = 142;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x80L);
      case 58:
         jjmatchedKind = 172;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x400000000000L);
      case 59:
         return jjStopAtPos(0, 177);
      case 60:
         jjmatchedKind = 148;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x42040000L);
      case 61:
         jjmatchedKind = 173;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10000010000L);
      case 62:
         jjmatchedKind = 149;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x84080000L);
      case 63:
         jjmatchedKind = 171;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0xf000000000L);
      case 91:
         return jjStopAtPos(0, 182);
      case 93:
         return jjStopAtPos(0, 183);
      case 94:
         jjmatchedKind = 162;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20000000L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x180L, 0xff00000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1e00L, 0x10000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xfe000L, 0x0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1f00000L, 0x60000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x3e000000L, 0x180000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xfc0000000L, 0xe00000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x7000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xfe000000000L, 0x18000000000L, 0x0L);
      case 106:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x300000000000L, 0x40000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1c00000000000L, 0x1f00000000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x1e000000000000L, 0xe000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1e0000000000000L, 0x10000000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0xe00000000000000L, 0xe0000000000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xf000000000000000L, 0x70000000000001fL, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3e0L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000fc00L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3000000000070000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc000000000080000L, 0x1L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x2L);
      case 123:
         return jjStopAtPos(0, 180);
      case 124:
         jjmatchedKind = 161;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10800000L);
      case 125:
         return jjStopAtPos(0, 181);
      case 126:
         return jjStopAtPos(0, 163);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active2 & 0x400000L) != 0L)
            return jjStopAtPos(1, 150);
         break;
      case 43:
         if ((active2 & 0x200L) != 0L)
            return jjStopAtPos(1, 137);
         break;
      case 45:
         if ((active2 & 0x400L) != 0L)
            return jjStopAtPos(1, 138);
         break;
      case 46:
         if ((active2 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 166);
         else if ((active2 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 170);
         break;
      case 58:
         if ((active2 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 174);
         break;
      case 60:
         if ((active2 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 158;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x2000000L);
      case 61:
         if ((active2 & 0x10L) != 0L)
            return jjStopAtPos(1, 132);
         else if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(1, 133);
         else if ((active2 & 0x40L) != 0L)
            return jjStopAtPos(1, 134);
         else if ((active2 & 0x80L) != 0L)
            return jjStopAtPos(1, 135);
         else if ((active2 & 0x100L) != 0L)
            return jjStopAtPos(1, 136);
         else if ((active2 & 0x10000L) != 0L)
            return jjStopAtPos(1, 144);
         else if ((active2 & 0x20000L) != 0L)
            return jjStopAtPos(1, 145);
         else if ((active2 & 0x40000L) != 0L)
            return jjStopAtPos(1, 146);
         else if ((active2 & 0x80000L) != 0L)
            return jjStopAtPos(1, 147);
         else if ((active2 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 155);
         else if ((active2 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 156);
         else if ((active2 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 157);
         break;
      case 62:
         if ((active2 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 159;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 168);
         else if ((active2 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 169);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x4000000L);
      case 63:
         if ((active2 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 165;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x1000000000L);
      case 91:
         if ((active2 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 167);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x20400040006200L, active1, 0x3010180000000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x1002000000000080L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100000000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2e00800000700000L, active1, 0x6e0041020000000L, active2, 0L);
      case 102:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 37, 1);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000018000L, active1, 0xc000000000080060L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000180000000L, active1, 0x200600010400L, active2, 0x3L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x202020000L, active1, 0x2000600800L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0L, active2, 0L);
      case 110:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 113, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0x70004000000L, active1, 0x800018000803000L, active2, 0L);
      case 111:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x301c010c0400L, active1, 0xc20000060000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L, active1, 0L, active2, 0L);
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000000L, active2, 0L);
      case 114:
         if ((active1 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 114;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000000000800L, active1, 0x8004802000180L, active2, 0L);
      case 115:
         if ((active0 & 0x100L) != 0L)
         {
            jjmatchedKind = 8;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 43, 1);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x500c000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xfL, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x109000000000000L, active1, 0x1000000000000L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000008000000L, active1, 0L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000010L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x30000000L, active1, 0x100000000L, active2, 0L);
      case 121:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L, active1, 0x40000200L, active2, 0L);
      case 124:
         if ((active2 & 0x800000L) != 0L)
            return jjStopAtPos(1, 151);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 61:
         if ((active2 & 0x2000000L) != 0L)
            return jjStopAtPos(2, 153);
         else if ((active2 & 0x4000000L) != 0L)
            return jjStopAtPos(2, 154);
         else if ((active2 & 0x1000000000L) != 0L)
            return jjStopAtPos(2, 164);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x2200000000028000L, active1, 0x8000003L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000100000L, active1, 0x20000001001000L, active2, 0L);
      case 100:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 84, 1);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 87, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8000000000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x14000008010800L, active1, 0xc000000200000000L, active2, 0x2L);
      case 102:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 58, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L, active1, 0L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000000L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0x10280004a8030L, active2, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000040400000L, active1, 0x1200000400240000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0x840100000000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000800c0000L, active1, 0x280040000400L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4080000200000400L, active1, 0x100006800000800L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x4010000000L, active1, 0x200L, active2, 0L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80000000000000L, active2, 0L);
      case 114:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 125, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000800000000L, active1, 0x1000000001004cL, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2002280L, active1, 0x20002000L, active2, 0L);
      case 116:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 51, 1);
         else if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 100, 1);
         else if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 106, 1);
         else if ((active1 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 110;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 122, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0x800061020005000L, active1, 0x810100000000L, active2, 0x1L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000L, active1, 0x80000080L, active2, 0L);
      case 119:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 1);
         break;
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 72, 1);
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000000L, active1, 0x4000000L, active2, 0L);
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000280200800L, active1, 0x8000800c0442000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L, active1, 0x2000000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x14000L, active1, 0x20000001L, active2, 0L);
      case 100:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 81, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000000L, active1, 0L, active2, 0L);
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 1);
         else if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 1);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 13, 1);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 1);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 1);
         else if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 98, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x8002460920400000L, active1, 0x208100101000200L, active2, 0L);
      case 103:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 1);
         break;
      case 104:
         if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 128, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L, active1, 0x8000004L, active2, 0L);
      case 107:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 1);
         break;
      case 108:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 1);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 48, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x2100004010000000L, active1, 0x200080000L, active2, 0x2L);
      case 109:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 1);
         else if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 99, 1);
         break;
      case 110:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 105, 1);
         else if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 126, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L, active1, 0x1800004008800L, active2, 0L);
      case 111:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 1);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 104, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x60000000204040L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000000000000L, active2, 0L);
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x4014000000000000L, active1, 0x8000000000000000L, active2, 0L);
      case 115:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 69, 1);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 89, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x40060000L, active1, 0L, active2, 0L);
      case 116:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 74, 1);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 103, 1);
         else if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 109, 1);
         return jjMoveStringLiteralDfa4_0(active0, 0x1080000000080080L, active1, 0x10000000010012L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000L, active1, 0x1080004000000008L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x44000800000000L, active1, 0x2000000000L, active2, 0L);
      case 99:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 90, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L, active1, 0x200000000000018L, active2, 0L);
      case 100:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 32, 1);
         else if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 97, 1);
         else if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 129, 1);
         break;
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 30, 1);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 1);
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 83, 1);
         else if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 124, 1);
         else if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 127, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x2080000000000000L, active1, 0x100000020001000L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2000L, active2, 0L);
      case 103:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 75, 1);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 79, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L, active1, 0x80000000000L, active2, 0L);
      case 104:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x100004010080000L, active1, 0x90000000000002L, active2, 0L);
      case 107:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L, active1, 0x1L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x81000000L, active1, 0x80000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000100000L, active1, 0x40000000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800000101000004L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x8200000000000000L, active1, 0x100000000200L, active2, 0L);
      case 112:
         if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 102, 1);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x810060020000080L, active1, 0x28000000004000L, active2, 0L);
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 17, 1);
         else if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 86, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 18, 1);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 1);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 33, 1);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 62, 1);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 91, 1);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 112, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L, active1, 0x800000010000L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40000000000000L, active2, 0L);
      case 119:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 70, 1);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x500080L, active1, 0x810000000010001L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000000000000L);
      case 99:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 56, 1);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(5, 65, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x80004810000000L, active1, 0x1000L);
      case 100:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 1);
         else if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 117, 1);
         else if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 120, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x1000000L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 1);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 77, 1);
         else if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 118, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L, active1, 0x80000000000L);
      case 102:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 63, 1);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 73, 1);
         else if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 108, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L, active1, 0L);
      case 103:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 66, 1);
         break;
      case 104:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000000L, active1, 0x40040000L);
      case 108:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 101, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x80200000L, active1, 0x800000000000L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 1);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 59, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x200040000080000L, active1, 0x20000000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000000000000L);
      case 115:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 53, 1);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 85, 1);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 95, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100000000L);
      case 116:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 49, 1);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(5, 67, 1);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 1);
         else if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 121, 1);
         return jjMoveStringLiteralDfa6_0(active0, 0x44000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x460000000000L, active1, 0L);
      case 99:
         if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 94, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x80L, active1, 0L);
      case 100:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 16, 1);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 107, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0x20000000L);
      case 101:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 54, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80000000000000L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800000000000000L);
      case 104:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 35, 1);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x4010000000L, active1, 0x101000000L);
      case 107:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000L);
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 1);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 80, 1);
         else if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 111, 1);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 116, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L, active1, 0x40001L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 1);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000400000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L, active1, 0L);
      case 121:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 1);
         else if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 115, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x420000000000L, active1, 0L);
      case 100:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 119, 1);
         break;
      case 101:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 1);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(7, 22, 1);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 52, 1);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(7, 82, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000000L, active1, 0x800000000001000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20000000L);
      case 108:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 42, 1);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x1L);
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x1000000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x100000000L);
      case 114:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 50, 1);
         break;
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 1);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 1);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 38, 1);
         break;
      case 121:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 55, 1);
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 76, 1);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 123, 1);
         break;
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 41, 1);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 46, 1);
         break;
      case 103:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(8, 88, 1);
         break;
      case 110:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(8, 96, 1);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20000000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(9, 64, 1);
         break;
      case 103:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(9, 93, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 102;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 72:
                  if (curChar == 42)
                     { jjCheckNAddStates(0, 2); }
                  else if (curChar == 47)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAdd(73); }
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(3, 8); }
                  else if (curChar == 36)
                     { jjAddStates(9, 10); }
                  else if (curChar == 47)
                     { jjAddStates(11, 12); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(13, 15); }
                  else if (curChar == 39)
                     { jjAddStates(16, 18); }
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 6;
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 188)
                        kind = 188;
                     { jjCheckNAddStates(19, 21); }
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 188)
                        kind = 188;
                     { jjCheckNAddStates(22, 25); }
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 130)
                     kind = 130;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 131)
                     kind = 131;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 5:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddStates(26, 28); }
                  break;
               case 9:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 13:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(19, 21); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(19, 21); }
                  break;
               case 21:
                  if (curChar == 39)
                     { jjAddStates(16, 18); }
                  break;
               case 22:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 23:
                  if (curChar == 39 && kind > 193)
                     kind = 193;
                  break;
               case 25:
                  if ((0x1008400000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(23, 29); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(29, 31); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(30, 23); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(30); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 44:
                  if (curChar == 34)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 45:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 47:
                  { jjCheckNAddStates(13, 15); }
                  break;
               case 48:
                  if (curChar == 34 && kind > 198)
                     kind = 198;
                  break;
               case 49:
                  if (curChar != 48)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(22, 25); }
                  break;
               case 51:
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 54:
               case 55:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(3, 8); }
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 58:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddStates(38, 40); }
                  break;
               case 62:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
               case 64:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(64, 12); }
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(65, 66); }
                  break;
               case 67:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(69, 12); }
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(70, 12); }
                  break;
               case 71:
                  if (curChar == 47)
                     { jjAddStates(11, 12); }
                  break;
               case 73:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(73); }
                  break;
               case 74:
                  if (curChar == 42)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 75:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 76:
                  if (curChar == 42)
                     { jjCheckNAddStates(41, 43); }
                  break;
               case 77:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddStates(44, 47); }
                  break;
               case 78:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(44, 47); }
                  break;
               case 79:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 80:
                  if (curChar == 36)
                     { jjAddStates(9, 10); }
                  break;
               case 82:
               case 84:
                  if (curChar == 34)
                     { jjCheckNAddStates(48, 50); }
                  break;
               case 83:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(48, 50); }
                  break;
               case 85:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 34 && kind > 195)
                     kind = 195;
                  break;
               case 87:
                  if (curChar == 34)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 88:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 90:
                  { jjCheckNAddStates(51, 55); }
                  break;
               case 95:
                  if (curChar == 34 && kind > 196)
                     kind = 196;
                  break;
               case 97:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 98:
                  if (curChar == 34)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 99:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(56, 58); }
                  break;
               case 100:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 101:
                  if (curChar == 34 && kind > 197)
                     kind = 197;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 130)
                        kind = 130;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 64)
                     { jjAddStates(59, 60); }
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 130)
                     kind = 130;
                  { jjCheckNAdd(1); }
                  break;
               case 2:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 131)
                     kind = 131;
                  { jjCheckNAdd(4); }
                  break;
               case 7:
                  if (curChar != 95)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddStates(26, 28); }
                  break;
               case 8:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(61, 62); }
                  break;
               case 11:
                  if (curChar != 95)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 12:
                  if ((0x205000002050L & l) != 0L && kind > 184)
                     kind = 184;
                  break;
               case 14:
                  if (curChar != 95)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(19, 21); }
                  break;
               case 15:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x100000001000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0x100000001000L & l) != 0L && kind > 188)
                     kind = 188;
                  break;
               case 18:
                  if ((0x100000001000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 19:
                  if ((0x100000001000L & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAdd(20); }
                  break;
               case 20:
                  if ((0x20000000200000L & l) != 0L && kind > 188)
                     kind = 188;
                  break;
               case 22:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 24:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x54404610000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 26:
                  if (curChar == 92)
                     { jjAddStates(63, 65); }
                  break;
               case 27:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddTwoStates(23, 29); }
                  break;
               case 29:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddStates(29, 31); }
                  break;
               case 30:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAddTwoStates(30, 23); }
                  break;
               case 32:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
               case 43:
                  if ((0x7e0000007eL & l) != 0L)
                     { jjCheckNAdd(30); }
                  break;
               case 36:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 46:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  { jjCheckNAddStates(13, 15); }
                  break;
               case 50:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 52:
                  if ((0x7e8000007eL & l) == 0L)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 53:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 55:
                  if (curChar != 95)
                     break;
                  if (kind > 188)
                     kind = 188;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 57:
                  if (curChar == 95)
                     { jjAddStates(66, 67); }
                  break;
               case 60:
                  if (curChar != 95)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddStates(38, 40); }
                  break;
               case 61:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               case 64:
                  if (curChar != 95)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(64, 12); }
                  break;
               case 65:
                  if (curChar == 95)
                     { jjAddStates(70, 71); }
                  break;
               case 66:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(72, 73); }
                  break;
               case 69:
                  if (curChar != 95)
                     break;
                  if (kind > 184)
                     kind = 184;
                  { jjCheckNAddTwoStates(69, 12); }
                  break;
               case 70:
                  if (curChar == 95)
                     { jjCheckNAddTwoStates(70, 12); }
                  break;
               case 73:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 77:
               case 78:
                  { jjCheckNAddStates(44, 47); }
                  break;
               case 81:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 83:
                  { jjAddStates(48, 50); }
                  break;
               case 88:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 89:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  { jjCheckNAddStates(51, 55); }
                  break;
               case 91:
                  if (curChar == 123)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 92:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 125)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 94:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
                  if (curChar == 64)
                     { jjAddStates(59, 60); }
                  break;
               case 99:
                  { jjAddStates(56, 58); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 45:
               case 47:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 73:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(0, 2); }
                  break;
               case 77:
               case 78:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(44, 47); }
                  break;
               case 83:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(48, 50); }
                  break;
               case 88:
               case 90:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(51, 55); }
                  break;
               case 99:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(56, 58); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 102 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\141\142\163\164\162\141\143\164", 
"\141\163", "\142\141\163\145", "\142\157\157\154", "\142\162\145\141\153", 
"\142\171\164\145", "\143\141\163\145", "\143\141\164\143\150", "\143\150\141\162", 
"\143\150\145\143\153\145\144", "\143\154\141\163\163", "\143\157\156\163\164", 
"\143\157\156\164\151\156\165\145", "\144\145\143\151\155\141\154", "\144\145\146\141\165\154\164", 
"\144\145\154\145\147\141\164\145", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\145\156\165\155", "\145\166\145\156\164", "\145\170\160\154\151\143\151\164", 
"\145\170\164\145\162\156", "\146\141\154\163\145", "\146\151\156\141\154\154\171", 
"\146\151\170\145\144", "\146\154\157\141\164", "\146\157\162", "\146\157\162\145\141\143\150", 
"\147\157\164\157", "\151\146", "\151\155\160\154\151\143\151\164", "\151\156", "\151\156\164", 
"\151\156\164\145\162\146\141\143\145", "\151\156\164\145\162\156\141\154", "\151\163", "\154\157\143\153", 
"\154\157\156\147", "\156\141\155\145\163\160\141\143\145", "\156\145\167", "\156\165\154\154", 
"\157\142\152\145\143\164", "\157\160\145\162\141\164\157\162", "\157\165\164", 
"\157\166\145\162\162\151\144\145", "\160\141\162\141\155\163", "\160\162\151\166\141\164\145", 
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\162\145\141\144\157\156\154\171", 
"\162\145\146", "\162\145\164\165\162\156", "\163\142\171\164\145", 
"\163\145\141\154\145\144", "\163\150\157\162\164", "\163\151\172\145\157\146", 
"\163\164\141\143\153\141\154\154\157\143", "\163\164\141\164\151\143", "\163\164\162\151\156\147", 
"\163\164\162\165\143\164", "\163\167\151\164\143\150", "\164\150\151\163", "\164\150\162\157\167", 
"\164\162\165\145", "\164\162\171", "\164\171\160\145\157\146", "\165\151\156\164", 
"\165\154\157\156\147", "\165\156\143\150\145\143\153\145\144", "\165\156\163\141\146\145", 
"\165\163\150\157\162\164", "\165\163\151\156\147", "\166\151\162\164\165\141\154", "\166\157\151\144", 
"\166\157\154\141\164\151\154\145", "\167\150\151\154\145", "\141\144\144", "\141\154\154\157\167\163", 
"\141\154\151\141\163", "\141\156\144", "\141\163\143\145\156\144\151\156\147", "\141\162\147\163", 
"\141\163\171\156\143", "\141\167\141\151\164", "\142\171", 
"\144\145\163\143\145\156\144\151\156\147", "\144\171\156\141\155\151\143", "\145\161\165\141\154\163", 
"\145\170\164\145\156\163\151\157\156", "\146\151\145\154\144", "\146\151\154\145", "\146\162\157\155", 
"\147\145\164", "\147\154\157\142\141\154", "\147\162\157\165\160", "\151\156\151\164", 
"\151\156\164\157", "\152\157\151\156", "\154\145\164", "\155\141\156\141\147\145\144", 
"\156\141\155\145\157\146", "\156\151\156\164", "\156\157\164", "\156\157\164\156\165\154\154", 
"\156\165\151\156\164", "\157\156", "\157\162", "\157\162\144\145\162\142\171", 
"\160\141\162\164\151\141\154", "\162\145\143\157\162\144", "\162\145\155\157\166\145", 
"\162\145\161\165\151\162\145\144", "\163\143\157\160\145\144", "\163\145\154\145\143\164", "\163\145\164", 
"\165\156\155\141\156\141\147\145\144", "\166\141\154\165\145", "\166\141\162", "\167\150\145\156", 
"\167\150\145\162\145", "\167\151\164\150", "\171\151\145\154\144", null, null, "\53\75", "\55\75", 
"\52\75", "\57\75", "\45\75", "\53\53", "\55\55", "\53", "\55", "\52", "\57", "\45", 
"\75\75", "\41\75", "\74\75", "\76\75", "\74", "\76", "\46\46", "\174\174", "\41", 
"\74\74\75", "\76\76\75", "\46\75", "\174\75", "\136\75", "\74\74", "\76\76", "\46", 
"\174", "\136", "\176", "\77\77\75", "\77\77", "\77\56", "\77\133", "\75\76", 
"\55\76", "\56\56", "\77", "\72", "\75", "\72\72", "\56", "\54", "\73", "\50", "\51", 
"\173", "\175", "\133", "\135", null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   75, 76, 79, 57, 58, 65, 66, 70, 12, 81, 87, 72, 74, 45, 46, 48, 
   22, 24, 26, 14, 15, 18, 50, 53, 15, 18, 7, 8, 12, 30, 23, 31, 
   52, 15, 18, 55, 15, 18, 60, 61, 12, 76, 77, 79, 76, 77, 78, 79, 
   83, 85, 86, 88, 89, 92, 94, 95, 99, 100, 101, 97, 98, 9, 10, 27, 
   32, 36, 57, 58, 62, 63, 65, 66, 67, 68, 
};

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public CSharpLexerTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public CSharpLexerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  static public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 102; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public static void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xffffffffffffffffL, 0x11ffffffffffffffL, 0x7aL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 0x0L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 0x0L, 0x0L, 
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[102];
    static private final int[] jjstateSet = new int[2 * 102];
    private static final StringBuilder jjimage = new StringBuilder();
    private static StringBuilder image = jjimage;
    private static int jjimageLen;
    private static int lengthOfMatch;
    static protected int curChar;
}
